language: r
dist: xenial

r:
  - release
  - devel

cache:
  - packages
  - ccache

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libhdf5-dev

r_packages:
  - goodpractice
  - rgdal

r_github_packages:
  - jimhester/covr
  - NEONScience/NEON-geolocation/geoNEON

script: 
  - |
    R CMD build .
    travis_wait 30 R CMD check *tar.gz

after_success:
    - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
