language: r
dist: xenial

r:
  - release
  - devel

cache:
  - packages
  - ccache

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libhdf5-dev

r_packages:
  - goodpractice
  - rgdal

r_github_packages:
  - jimhester/covr
  - NEONScience/NEON-geolocation/geoNEON
  - NEONScience/NEON-utilities/neonUtilities
  
script:
  - travis wait R CMD build .
  - travis wait R CMD check *tar.gz

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'goodpractice::gp()'

notifications:
  email:
    on_success: change
    on_failure: change
